import { BadRequestException, Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
type FacebookApiError={message?:string;type?:string;code?:number;error_subcode?:number;fbtrace_id?:string};
type FacebookApiResponse<T>=T&{error?:FacebookApiError};
type FacebookPage={id:string;name:string;username?:string;link?:string;category?:string;fan_count?:number};
type FacebookPostResult={id:string};type FacebookPhotoResult={id:string;post_id?:string};
@Injectable()
export class FacebookConnectorService{
 constructor(private readonly configService:ConfigService){}
 async testConnection(){const page=await this.graphGet<FacebookPage>(this.getPageId(),{fields:['id','name','username','link','category','fan_count'].join(',')});return{connected:true,page:{id:page.id,name:page.name,username:page.username??null,link:page.link??null,category:page.category??null,followers:page.fan_count??null},graphApiVersion:this.getApiVersion()}}
 async sendTestPost(){const result=await this.publishPost('✅ Atlas Facebook connection test successful.');return{published:true,postId:result.id,pageId:this.getPageId(),publishedAt:new Date().toISOString()}}
 async publish(message:string,mediaUrls:string[]=[],link?:string){const first=mediaUrls.map(url=>url?.trim()).find(Boolean);return first?this.publishPhoto(message,first):this.publishPost(message,link)}
 async publishPhoto(caption:string,mediaUrl:string){const clean=caption?.trim();if(!clean)throw new BadRequestException('Facebook caption cannot be empty.');const media=await this.fetchMedia(mediaUrl);const form=new FormData();form.set('caption',clean);form.set('access_token',this.getAccessToken());form.set('source',media.blob,media.filename);const response=await fetch(`${this.getBaseUrl()}/${this.getPageId()}/photos`,{method:'POST',body:form});const result=await response.json() as FacebookApiResponse<FacebookPhotoResult>;this.throwFacebookError(response.ok,result.error);return result}
 async publishPost(message:string,link?:string){const clean=message?.trim();if(!clean)throw new BadRequestException('Facebook message cannot be empty.');const payload:Record<string,string>={message:clean};if(link?.trim())payload.link=link.trim();return this.graphPost<FacebookPostResult>(`${this.getPageId()}/feed`,payload)}
 private async fetchMedia(mediaUrl:string){const clean=mediaUrl?.trim();if(!clean)throw new BadRequestException('Facebook media URL is required.');if(clean.startsWith('data:image/'))return this.dataImage(clean,'atlas-sports-news');let response:Response;try{response=await fetch(clean)}catch(error){throw new BadRequestException(`Unable to read Facebook media: ${error instanceof Error?error.message:'Unknown media fetch error'}`)}if(!response.ok)throw new BadRequestException(`Unable to read Facebook media. HTTP ${response.status}`);const type=response.headers.get('content-type')||'application/octet-stream';if(!type.startsWith('image/'))throw new BadRequestException(`Facebook media must be an image. Received ${type}.`);const pathname=new URL(clean).pathname;const filename=pathname.split('/').pop()||'atlas-image';return{filename,blob:new Blob([await response.arrayBuffer()],{type})}}
 private dataImage(value:string,name:string){const match=/^data:(image\/[a-zA-Z0-9.+-]+);base64,(.+)$/.exec(value);if(!match)throw new BadRequestException('Invalid generated image data.');const type=match[1];const bytes=Buffer.from(match[2],'base64');const ext=type==='image/jpeg'?'jpg':type.split('/')[1]?.replace('jpeg','jpg')||'png';return{filename:`${name}.${ext}`,blob:new Blob([bytes],{type})}}
 private getPageId(){const id=this.configService.get<string>('FACEBOOK_PAGE_ID');if(!id?.trim()||id==='PASTE_YOUR_PAGE_ID_HERE')throw new BadRequestException('FACEBOOK_PAGE_ID is not configured.');return id.trim()}
 private getAccessToken(){const token=this.configService.get<string>('FACEBOOK_PAGE_ACCESS_TOKEN');if(!token?.trim()||token==='PASTE_YOUR_PAGE_ACCESS_TOKEN_HERE')throw new BadRequestException('FACEBOOK_PAGE_ACCESS_TOKEN is not configured.');return token.trim()}
 private getApiVersion(){return this.configService.get<string>('FACEBOOK_GRAPH_API_VERSION')?.trim()||'v23.0'}
 private getBaseUrl(){return `https://graph.facebook.com/${this.getApiVersion()}`}
 private async graphGet<T>(path:string,query:Record<string,string>):Promise<T>{const url=new URL(`${this.getBaseUrl()}/${path}`);for(const[key,value]of Object.entries(query))url.searchParams.set(key,value);url.searchParams.set('access_token',this.getAccessToken());const response=await fetch(url);const body=await response.json() as FacebookApiResponse<T>;this.throwFacebookError(response.ok,body.error);return body as T}
 private async graphPost<T>(path:string,payload:Record<string,string>):Promise<T>{const body=new URLSearchParams({...payload,access_token:this.getAccessToken()});const response=await fetch(`${this.getBaseUrl()}/${path}`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const result=await response.json() as FacebookApiResponse<T>;this.throwFacebookError(response.ok,result.error);return result as T}
 private throwFacebookError(ok:boolean,error?:FacebookApiError){if(ok&&!error)return;throw new BadRequestException(error?.message||'Facebook Graph API request failed.')}
}
