ALTER TABLE "SportsNewsSetting"
ADD COLUMN "logoAssetId" TEXT,
ADD COLUMN "logoSize" TEXT NOT NULL DEFAULT 'small',
ADD COLUMN "logoOpacity" INTEGER NOT NULL DEFAULT 90,
ADD COLUMN "logoMargin" INTEGER NOT NULL DEFAULT 32;
