ALTER TABLE "ImageGenerationSetting"
ADD COLUMN "cornerLogoEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "cornerLogoPlacement" TEXT NOT NULL DEFAULT 'TOP_RIGHT',
ADD COLUMN "cornerLogoScale" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN "cornerLogoOpacity" DOUBLE PRECISION NOT NULL DEFAULT 1;
