ALTER TABLE "AiRuntimeSetting"
ADD COLUMN IF NOT EXISTS "aiStudioModel" TEXT NOT NULL DEFAULT 'gpt-5.6-luna',
ADD COLUMN IF NOT EXISTS "aiStudioInstructions" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "aiStudioTimeoutMs" INTEGER NOT NULL DEFAULT 30000,
ADD COLUMN IF NOT EXISTS "aiStudioRetryLimit" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "copilotModel" TEXT NOT NULL DEFAULT 'gpt-5.6-luna',
ADD COLUMN IF NOT EXISTS "copilotInstructions" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "copilotKnowledgeLimit" INTEGER NOT NULL DEFAULT 4,
ADD COLUMN IF NOT EXISTS "copilotConversationRecallLimit" INTEGER NOT NULL DEFAULT 7,
ADD COLUMN IF NOT EXISTS "copilotStudioHistoryLimit" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN IF NOT EXISTS "copilotContextMaxChars" INTEGER NOT NULL DEFAULT 7500;
